version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@86.107.45.160:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
