"""migrate

Revision ID: 80ab50aff68b
Revises: 70ea8c5f3fff
Create Date: 2024-05-27 16:14:30.526333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ab50aff68b'
down_revision: Union[str, None] = '70ea8c5f3fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('local', sa.String(), nullable=False))
    op.add_column('products', sa.Column('local', sa.String(), nullable=False))
    op.add_column('types', sa.Column('local', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'local')
    op.drop_column('products', 'local')
    op.drop_column('categories', 'local')
    # ### end Alembic commands ###
