"""initial_migration

Revision ID: d70cc1d73985
Revises: 2c080b263d9d
Create Date: 2024-04-24 20:04:32.366965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd70cc1d73985'
down_revision: Union[str, None] = '2c080b263d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
