"""Change Type.category relationship to uselist=False

Revision ID: ef425b7475e1
Revises: fdb056515a21
Create Date: 2024-05-21 18:28:05.009491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef425b7475e1'
down_revision: Union[str, None] = 'fdb056515a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
